### ISSUE TITLE
Try not to use append() for the ODE solvers in Python 

### ISSUE THREAD

**Issue by hamidrezanorouzi** [hamidrezanorouzi/numericalMethods#3]
Can we change the code to eliminate y.append() and x.append() statements in the ODE solvers. Since, in the text book we use yi+1 and yi to show how we march over independent variable and here we use append to add yi+1 to the solution. 
A hint: You may pre-allocate the whole vector length (or more) and return the fraction that contains the solution.

**Comment by ErfanTabatabaee** [comment]
it's Done!
